# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
            ],
        ),
    ]
