# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_chemistry_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chemistry',
        ),
        migrations.DeleteModel(
            name='Physics',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
