# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_chemistry_physics_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(1, 'Physics'), (2, 'Chemistry'), (3, 'Projects')], max_length=1)),
                ('topics', models.TextField()),
                ('theory', models.TextField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Chemistry',
        ),
        migrations.DeleteModel(
            name='Physics',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
