# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160624_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='image',
        ),
        migrations.AddField(
            model_name='subjects',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjects',
            name='topics',
            field=models.CharField(max_length=100),
        ),
    ]
