# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20160624_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Explanation',
            new_name='Explain',
        ),
        migrations.RenameField(
            model_name='explain',
            old_name='subject_id',
            new_name='sub',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
