# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20160624_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='explain',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
