# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 17:59
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_explain_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='explain',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
    ]
