# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_explain_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explain',
            name='video',
        ),
    ]
